### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by huangming1994** [mc-zone/IDValidator#2]
我用了您的idValidator，好像有一点点的小bug，有些身份证在输入到15位时，自动带入的birth是错误的~好像输入正确的18位，调用了getInfo，正确带入了生日性别之后，我再次删除一位数字，boom。。我屏蔽了15位的代码。。好像是没问题了。。

**Comment by mc-zone** [comment]
你是在oninput时候不断验证吗？这样没法区分你是在输入15位的还是18位的。

**Comment by mc-zone** [comment]
![image](https://cloud.githubusercontent.com/assets/4403937/20487940/43e41756-b040-11e6-9455-87e699c427dd.png)
![image](https://cloud.githubusercontent.com/assets/4403937/20487942/47af364a-b040-11e6-99ec-69e64b58ce5c.png)
这两种这两种号码都是存在的。

**Comment by mc-zone** [comment]
![image](https://cloud.githubusercontent.com/assets/4403937/20488097/c5c134f2-b040-11e6-966a-ac5013b559b1.png)

![image](https://cloud.githubusercontent.com/assets/4403937/20488076/b6346cac-b040-11e6-8919-7eecfc5799bb.png)


这两种号码都是存在的。

**Comment by mc-zone** [comment]
@huangming1994 刚改了下，已支持限定类型的验证。用最新版本即可。

```javascript
//强制要求18位ID
Validator.isValid( id,18 );
Validator.getInfo( id,18 );
```
